<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-056FM3MC" failures="1" tests="3" name="Test" time="15.132" errors="0" timestamp="2021-12-29T17:49:52 IST">
  <testcase classname="assignments.Assignment2" name="navigateToWallethub" time="4.319"/>
  <testcase classname="assignments.Assignment2" name="loginWallethub" time="2.847"/>
  <testcase classname="assignments.Assignment2" name="addReviewWallethub" time="5.45">
    <failure type="java.lang.AssertionError" message="You have already given review. Please use a new user. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: You have already given review. Please use a new user. expected [false] but found [true]
at com.wallethub.pageObjects.WalletHub_ReviewPage.checkIfReviewed(WalletHub_ReviewPage.java:92)
at assignments.Assignment2.addReviewWallethub(Assignment2.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- addReviewWallethub -->
</testsuite> <!-- Test -->
